### ISSUE TITLE
Seeking Guidance on SLKB Usage

### ISSUE THREAD

**Issue by Rohak72** [BirkanGokbag/SLKB-Analysis-Pipeline#1]
Hi @BirkanGokbag,

First off, thank you so much for creating such an in-depth tool for the holistic analysis of SL pairs -- it really is a tremendous help! I'm currently working on a project that is attempting to identify conserved SL pairs among flaviviruses (i.e. dengue, hepatitis C, etc.) to engineer pan-viral therapies that will survive the test of mutations and other genetic abnormalities. For this purpose, I'm planning to construct infection- and baseline-specific metabolic models that will represent key elements of metabolism (e.g. essential metabolites, genes, reactions) based on input transcriptome data corresponding to the various conditions (treated vs. untreated). After constructing these models, I'm using a software called Fast-SL to infer double- and triple-lethal SLs. 

So, my question is: how could I take those lists of SL pairs and triplets, run those by SLKB's tools, and come up with a confidence score / ranking metric that helps me decide which to prioritize or focus on in-depth? After reading through the SLKB paper and visiting the official website, I found the 'Browse Study Reported Scores' page really comprehensive and helpful. It seems if you turn on the 'SL pairs' toggle, you're essentially given a dataframe with the SL pairs, the study/cell-line, and relevant statistical scores. Would it be worth it to download this data and cross-reference it with the SL lists I mentioned above? Or would there be a more rigorous analysis that you recommend?

Please let me know your thoughts! Again, thanks so much for developing this -- I'm excited to see what possibilities this holds.

Best,
Rohak

**Comment by BirkanGokbag** [comment]
Hi Rohak,

Thank you for reaching out, I hope our paper can help with your research! As you had mentioned, you can use scores already deposited in SLKB and furthermore use the software included in the paper for your analysis as well. It depends on your use case, but you can run different scoring approaches or employ your own designed scoring approach on the CDKO data you may have. 

You can access the documentation website that can help you get started for all the analyses you have mentioned, and the deposited data has both 'SL' and 'Not SL' annotations for your gene pair queries. To add, there are SL gene pairs that are specific to screenings and cell lines. If you are interested in conserved SL pairs, you may wish to start by comparing and contrasting SL pairs in different contexts as you mentioned. 

You can look at overlapped rankings on your analyzed data as described in the paper, perhaps it may lead you to identify gene pairs that have high confidence in being synthetic lethal (e.g., identified as top SL across multiple approaches). You can use the shared web application for this task, included within the python package. I hope this helps! 

Best,

Birkan
